### ISSUE TITLE
ApplicationInsightsMiddleware.process_template_response didn't return an HttpResponse object.

### ISSUE THREAD

**Issue by dopic** [Microsoft/ApplicationInsights-Python#51] opened 2017-09-06 02:05 UTC
Hi, 

When my response has a render() method (Django's TemplateResponse), it throws the following exception:

**ApplicationInsightsMiddleware.process_template_response didn't return an HttpResponse object. It returned None instead.**

If I return the response object in method process_template_response from django's middleware, it works fine.

Thanks

**Comment by jjjordanmsft** [comment] 2017-09-06 23:36
This is a dupe of #46.  There's a wheel at that bug report until we can put out a version that fixes this.  Sorry for the delay.

**Comment by dopic** [comment] 2017-09-07 00:37
Ok! I'll close this one.
Thanks!

**Closed** 2017-09-07 00:37 UTC

**Comment by jjjordanmsft** [comment] 2017-09-07 00:54
Jumped the gun on offering a workaround.  I've just pushed 0.11.1 to pypi which has this fix.
